const names=['武德真經','金剛般若波羅蜜經','藥師琉璃光如來本願功德經','地藏菩薩本願經','般若波羅蜜多心經'];
const $=s=>document.querySelector(s); const key='offline-chant-web-v1';
const state=JSON.parse(localStorage.getItem(key)||'{"goals":[9,9,9,9,9],"records":{}}');
const today=new Date().toISOString().slice(0,10); $('#date').value=today;
function lunar(date){const [y,m,d]=date.split('-').map(Number);return Solar.fromYmd(y,m,d).getLunar()}
function lunarYear(date){return lunar(date).getYear()-1911}
function lunarMonthKey(date){const x=lunar(date);return `${x.getYear()}-${x.getMonth()}`}
function daysUntilNextLunarFirst(date){const start=new Date(`${date}T00:00:00`);for(let days=1;days<=31;days+=1){const candidate=new Date(start);candidate.setDate(candidate.getDate()+days);const x=Solar.fromYmd(candidate.getFullYear(),candidate.getMonth()+1,candidate.getDate()).getLunar();if(x.getDay()===1)return days}return 0}
function saveState(){localStorage.setItem(key,JSON.stringify(state))}
function totals(filter){const out=[0,0,0,0,0];Object.entries(state.records).filter(([date])=>filter(date)).forEach(([,v])=>v.forEach((n,i)=>out[i]+=n));return out}
function cards(target, values, goals){target.innerHTML=MonthlyView.monthlyDetailsMarkup(names,values,goals)}
function monthlyBoard(target, values, goals){target.className='board';target.innerHTML=names.map((name,i)=>`<div class="board-row"><span class="pin">●</span><span class="board-name">${name}</span><strong class="board-count">${values[i]} <small>/ ${goals[i]} 部</small></strong><progress class="board-progress" max="${goals[i]}" value="${Math.min(values[i],goals[i])}"></progress></div>`).join('')}
function annualList(target, values){target.className='';target.innerHTML=AnnualView.annualDetailsMarkup(names,values)}
function render(){const date=$('#date').value;const l=lunar(date);$('#lunar').textContent=`農曆 ${l.toString()}`;const counts=state.records[date]||[0,0,0,0,0];const days=daysUntilNextLunarFirst(date);const countdown=$('#monthCountdown');countdown.textContent=`距結算 ${days} 天`;countdown.className=days<=5?'urgent':'normal';$('#inputs').innerHTML=names.map((n,i)=>`<label>${n}<input class="count" type="number" min="0" inputmode="numeric" value="${counts[i]}"></label>`).join('');const monthlyValues=totals(d=>lunarMonthKey(d)===lunarMonthKey(date));$('#monthTotal').textContent=`本月合計：${monthlyValues.reduce((sum,value)=>sum+value,0)} / ${state.goals.reduce((sum,value)=>sum+value,0)} 部`;const monthly=$('#monthly');monthly.className='';cards(monthly,monthlyValues,state.goals);const year=lunarYear(date);$('#yearTitle').textContent=`年度統計（民國 ${year} 年・農曆）`;const annual=totals(d=>lunarYear(d)===year);$('#yearTotal').textContent=`年度總和：${annual.reduce((a,b)=>a+b,0)} 部`;annualList($('#annual'),annual)}
$('#date').addEventListener('change',render);$('#save').onclick=()=>{state.records[$('#date').value]=[...document.querySelectorAll('.count')].map(x=>Math.max(0,parseInt(x.value||0,10)));saveState();render();alert('已儲存到此裝置。')};
$('#settings').onclick=()=>{const box=$('#goalInputs');box.innerHTML=names.map((n,i)=>`<label>${n}（部）<input class="goal" type="number" min="1" value="${state.goals[i]}"></label>`).join('');$('#goalDialog').showModal()};$('#cancel').onclick=()=>$('#goalDialog').close();$('#saveGoals').onclick=()=>{const goals=[...document.querySelectorAll('.goal')].map(x=>parseInt(x.value,10));if(goals.some(x=>!Number.isInteger(x)||x<1))return alert('請輸入大於 0 的整數。');state.goals=goals;saveState();$('#goalDialog').close();render()};
function downloadBackup(){const backup=ChantBackup.createBackup(state);const data=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(data);link.download=ChantBackup.backupFilename();link.click();URL.revokeObjectURL(link.href);$('#backupDialog').close();alert('備份檔已匯出。')}
async function importBackup(file){try{const restored=ChantBackup.restoreBackup(await file.text());if(!confirm('匯入備份會覆蓋此手機目前的月目標與所有持誦紀錄，確定要繼續嗎？'))return;Object.assign(state,restored);saveState();render();$('#backupDialog').close();alert('備份已匯入完成。')}catch(error){alert(error.message)}}
$('#backup').onclick=()=>$('#backupDialog').showModal();$('#cancelBackup').onclick=()=>$('#backupDialog').close();$('#exportBackup').onclick=downloadBackup;$('#importBackup').onclick=()=>$('#backupFile').click();$('#backupFile').addEventListener('change',event=>{const [file]=event.target.files;if(file)importBackup(file);event.target.value=''});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
